# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [5]:
import numpy as np
arr = np.random.uniform(0, 20, 28).reshape(4,7)
arr1 = (arr - np.min(arr))/(np.max(arr)-np.min(arr))
print(arr1)

[[2.41849307e-01 4.94608504e-01 8.30612666e-01 8.13869164e-01
  0.00000000e+00 8.69222594e-01 4.18647412e-01]
 [1.00000000e+00 2.29348605e-01 1.26405790e-01 3.78623556e-03
  2.42285451e-01 1.03972843e-01 3.47263414e-01]
 [8.23256899e-01 1.52202422e-02 6.81323891e-04 1.76476246e-02
  2.63494598e-01 7.89653684e-01 2.01597099e-01]
 [6.15182385e-01 6.06380519e-01 6.00761064e-01 7.19814898e-01
  3.49293387e-01 1.57481741e-01 7.09833846e-02]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [29]:
a = np.random.randint(0,10,80).reshape(8,10)
a.sum(axis=1)
print(a.sum(axis=1))

[58 49 41 41 46 56 55 39]


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [30]:
p1 = np.array((0, 0, 0))
p2 = np.array((3, 3, 3))
evk = np.sqrt(np.sum(np.square(p2-p1)))
print(evk)

5.196152422706632


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [31]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])
X = np.linalg.inv(A) @ (C*-1) @ np.linalg.inv(B)
print(X)

[[ 1.00000000e+00  5.32907052e-16]
 [-2.00000000e+00  1.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [6]:
zagolovok = np.loadtxt('/content/minutes_n_ingredients.csv', delimiter=',', dtype=str)[0]
a = np.loadtxt('/content/minutes_n_ingredients.csv', delimiter=',', dtype='int32', skiprows=1)
print(a[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [32]:
print('среднее значение:\n', zagolovok[1], np.mean(a[:,1]),'\n',zagolovok[2], np.mean(a[:,2]))
print('минимум:\n', zagolovok[1], a.min(axis=0)[1], '\n', zagolovok[2], a.min(axis=0)[2])
print('максимум:\n', zagolovok[1], a.max(axis=0)[1], '\n', zagolovok[2], a.max(axis=0)[2])
print(len(a))
print('медиана:\n', zagolovok[1], np.median(a[:,1]),'\n', zagolovok[2], np.median(a[:,2]))

среднее значение:
 minutes 5.0 
 n_ingredients 5.375
минимум:
 minutes 0 
 n_ingredients 2
максимум:
 minutes 9 
 n_ingredients 9
8
медиана:
 minutes 6.0 
 n_ingredients 5.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [ ]:
q = np.quantile(a,0.75, axis=0)[1]
a[:,1] = np.where(a[:,1]<=q, a[:,1], q)
print(a)

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993     65     14]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [ ]:
print(np.count_nonzero(a[:,1] == 0))
a[:, 1] = np.where(a[:, 1] != 0, a[:, 1], 1)
print(a)

479
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993    140     14]]


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [ ]:
print(len(np.unique(a[:,0])))

100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [ ]:
print(len(np.unique(a[:,2])), '\n', np.unique(a[:,2]),)

37 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [ ]:
b = a[np.where(a[:, 2]<=5)]
print(b)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [ ]:
print(a[:,2]/a[:,1])
print(max(a[:,2]/a[:,1]))

[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.21538462]
24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [ ]:
sorted(a[:,1], reverse=True)
print(np.mean(a[:100,2]))

8.43


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [ ]:
spisok = np.random.choice(len(a), size=10)
print(a[spisok, :])

[[ 58959     40      5]
 [384378      5      8]
 [312000     45     12]
 [210242     60      9]
 [138244     35      6]
 [ 31632     30     11]
 [472285     22     14]
 [ 69236     65      5]
 [ 94987     50      7]
 [   492     15      6]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [ ]:
ing_sr = np.mean(a[:,2])
print(len(a[np.where(a[:,2]<ing_sr)])/len(a)*100)

58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [ ]:
a1 = np.hstack((a,np.zeros((100000,1), dtype='int')))
a1[:,3] = np.where((a1[:,1]<=20) & (a1[:,2]<=5), 1, 0)
print(a1)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [ ]:
print(len(a1[np.where(a1[:,3]==1)])/len(a1)*100)

9.552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [28]:
maxx = min(len(a[np.where((a[:,1]<=10))]), len(a[np.where((a[:,1]>10) & (a[:,1]<20))]), len(a[np.where((a[:,1]>=20))]))
a2 = np.arange(maxx*3*3).reshape(3,maxx,3)
a2[0,:,:] = a[np.where((a[:,1]<=10))][:maxx]
a2[1,:,:] = a[np.where((a[:,1]>10) & (a[:,1]<20))][:maxx]
a2[2,:,:] = a[np.where((a[:,1]>=20))][:maxx]
print(a2)

[[[ 94746     10      6]
  [ 67660      5      6]
  [366174      7      9]
  ...
  [  7983      0      6]
  [184171      5      2]
  [ 89181      5      7]]

 [[ 33941     18      9]
  [446597     15      5]
  [ 81006     12      7]
  ...
  [ 44120     17      5]
  [ 60756     15      5]
  [128811     15      4]]

 [[127244     60     16]
  [ 23891     25      7]
  [157911     60     14]
  ...
  [186515    220     11]
  [372540     50      6]
  [172926    120     13]]]
